#!/bin/bash
dummy= #_G and nil --[[
   script=$(readlink -f "$0")
   origin=${script%/*}
   completions=/dev/null
   [ -f $origin/completions ] && completions=$origin/completions
#  Uncomment below if libelf, libluajit, libreadline, and rlwrap live here.
#  export LD_LIBRARY_PATH=$origin
#  export PATH=$origin:$PATH
   exec rlwrap -b ":(){}[],+-=&^%$#@\"';|\\"  \
               -f $completions               \
               -c -H $HOME/.${script##*/}_history \
               lua -i "$script" "$@"
#--]]

local origin=(arg and (arg[0]:match '^(.*)/') or '.')

package.path=origin..'/?.lua'..';'..package.path
package.cpath=origin..'/?.so'..';'..package.cpath
elfutil=require 'elfutil'
marshal=require 'freezer'
pp=require 'pprint'
function pt(t,l) io.write(pp.pformat(t, {depth_limit = l or 1}),'\n') end

require 'dltool'

-- Local Variables:
-- mode: lua
-- End:
